/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'mitnehmen-page': MitnehmenPage;
    'cafe-page': CafePage;
    'bestellen-page': BestellenPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'mitnehmen-page': MitnehmenPageSelect<false> | MitnehmenPageSelect<true>;
    'cafe-page': CafePageSelect<false> | CafePageSelect<true>;
    'bestellen-page': BestellenPageSelect<false> | BestellenPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    columns?:
      | {
          label: string;
          value: string;
          href?: string | null;
          wide?: boolean | null;
          id?: string | null;
        }[]
      | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  offerings: {
    eyebrow: string;
    heading: string;
    intro: string;
    cards?:
      | {
          number: string;
          title: string;
          description: string;
          href: string;
          cta: string;
          image: number | Media;
          icon: 'cake' | 'coffee' | 'cupcake' | 'bread';
          id?: string | null;
        }[]
      | null;
  };
  about: {
    eyebrow: string;
    quote: string;
    paragraph1: string;
    paragraph2: string;
    closing: string;
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    eyebrow: string;
    heading: string;
    text: string;
    image: number | Media;
    umgebung?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitnehmen-page".
 */
export interface MitnehmenPage {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    lede: string;
    primaryImage: number | Media;
    secondaryImage?: (number | null) | Media;
  };
  vitrine: {
    eyebrow: string;
    heading: string;
    intro?: string | null;
    items?:
      | {
          title: string;
          text?: string | null;
          image: number | Media;
          icon?: ('none' | 'cake' | 'coffee' | 'cupcake' | 'bread') | null;
          id?: string | null;
        }[]
      | null;
  };
  infoBand: {
    eyebrow: string;
    heading: string;
    body?: string | null;
    facts?:
      | {
          heading: string;
          lines?:
            | {
                text: string;
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cafe-page".
 */
export interface CafePage {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    lede: string;
    primaryImage: number | Media;
    secondaryImage?: (number | null) | Media;
  };
  experience: {
    eyebrow: string;
    heading: string;
    intro?: string | null;
    items?:
      | {
          title: string;
          text?: string | null;
          image: number | Media;
          icon?: ('none' | 'cake' | 'coffee' | 'cupcake' | 'bread') | null;
          id?: string | null;
        }[]
      | null;
  };
  rooms: {
    eyebrow: string;
    heading: string;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  infoBand: {
    eyebrow: string;
    heading: string;
    body?: string | null;
    facts?:
      | {
          heading: string;
          lines?:
            | {
                text: string;
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bestellen-page".
 */
export interface BestellenPage {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    lede: string;
    primaryImage: number | Media;
    secondaryImage?: (number | null) | Media;
  };
  steps: {
    eyebrow: string;
    heading: string;
    items?:
      | {
          number: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  occasions: {
    eyebrow: string;
    heading: string;
    intro?: string | null;
    items?:
      | {
          title: string;
          text?: string | null;
          image: number | Media;
          icon?: ('none' | 'cake' | 'coffee' | 'cupcake' | 'bread') | null;
          id?: string | null;
        }[]
      | null;
  };
  teeraum: {
    eyebrow: string;
    heading: string;
    body: string;
    image: number | Media;
    facts?:
      | {
          heading: string;
          lines: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  contact: {
    street: string;
    city: string;
    phoneDisplay: string;
    phoneNumber: string;
    faxDisplay?: string | null;
    instagramHandle: string;
    instagramUrl: string;
    mapsLink: string;
    mapsEmbedSrc: string;
  };
  hours?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  tagline: string;
  quote: string;
  companyName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        columns?:
          | T
          | {
              label?: T;
              value?: T;
              href?: T;
              wide?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  offerings?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        cards?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              href?: T;
              cta?: T;
              image?: T;
              icon?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        eyebrow?: T;
        quote?: T;
        paragraph1?: T;
        paragraph2?: T;
        closing?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        image?: T;
        umgebung?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mitnehmen-page_select".
 */
export interface MitnehmenPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        primaryImage?: T;
        secondaryImage?: T;
      };
  vitrine?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              icon?: T;
              id?: T;
            };
      };
  infoBand?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        facts?:
          | T
          | {
              heading?: T;
              lines?:
                | T
                | {
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cafe-page_select".
 */
export interface CafePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        primaryImage?: T;
        secondaryImage?: T;
      };
  experience?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              icon?: T;
              id?: T;
            };
      };
  rooms?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  infoBand?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        facts?:
          | T
          | {
              heading?: T;
              lines?:
                | T
                | {
                    text?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bestellen-page_select".
 */
export interface BestellenPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        primaryImage?: T;
        secondaryImage?: T;
      };
  steps?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  occasions?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              icon?: T;
              id?: T;
            };
      };
  teeraum?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        facts?:
          | T
          | {
              heading?: T;
              lines?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  contact?:
    | T
    | {
        street?: T;
        city?: T;
        phoneDisplay?: T;
        phoneNumber?: T;
        faxDisplay?: T;
        instagramHandle?: T;
        instagramUrl?: T;
        mapsLink?: T;
        mapsEmbedSrc?: T;
      };
  hours?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  tagline?: T;
  quote?: T;
  companyName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}